spring:
  cache:
    redis:
      type: redis
      redis:
        cache-null-values: false
        use-key-prefix: true
        time-to-live: 300000ms
  data:
    redis:
      host: redis-15051.c1.ap-southeast-1-1.ec2.cloud.redislabs.com
      port: 15051
      username: default
      password: AfIEmkGHR5fGdSj2kDTtdwDgMDJfQgVL